var mime_samples = [
  { 'mime': 'application/pdf', 'samples': [
    { 'url': 'http://www.aviadores.net/normativa/convenio_chicago.pdf', 'dir': '_m0/0', 'linked': 2, 'len': 400000 },
    { 'url': 'http://www.aviadores.net/normativa/entidades_colaboradoras.pdf', 'dir': '_m0/1', 'linked': 2, 'len': 228332 },
    { 'url': 'http://www.aviadores.net/normativa/EscritoParteMNTAC.pdf', 'dir': '_m0/2', 'linked': 2, 'len': 200627 },
    { 'url': 'http://www.aviadores.net/normativa/JARFCL1Indice1.pdf', 'dir': '_m0/3', 'linked': 2, 'len': 336198 },
    { 'url': 'http://www.aviadores.net/normativa/JARFCL1SUBB.pdf', 'dir': '_m0/4', 'linked': 2, 'len': 53133 },
    { 'url': 'http://www.aviadores.net/normativa/JARFCL1SUBC.pdf', 'dir': '_m0/5', 'linked': 2, 'len': 261490 },
    { 'url': 'http://www.aviadores.net/normativa/JARFCL1SUBE.pdf', 'dir': '_m0/6', 'linked': 2, 'len': 235317 },
    { 'url': 'http://www.aviadores.net/normativa/JARFCL1SUBF.pdf', 'dir': '_m0/7', 'linked': 2, 'len': 400000 },
    { 'url': 'http://www.aviadores.net/normativa/JARFCL3SUBA.pdf', 'dir': '_m0/8', 'linked': 2, 'len': 131242 },
    { 'url': 'http://www.aviadores.net/normativa/JARFCL3SUBC.pdf', 'dir': '_m0/9', 'linked': 2, 'len': 148815 },
    { 'url': 'http://www.aviadores.net/normativa/mantenimiento_aeronaves2.pdf', 'dir': '_m0/10', 'linked': 2, 'len': 400000 },
    { 'url': 'http://www.aviadores.net/normativa/ord_pre_2733_06_mod_RCA.pdf', 'dir': '_m0/11', 'linked': 2, 'len': 336516 },
    { 'url': 'http://www.aviadores.net/normativa/ord_pre_2912_05_mod_RCA.pdf', 'dir': '_m0/12', 'linked': 2, 'len': 184995 },
    { 'url': 'http://www.aviadores.net/normativa/ord_pre_4063_06_mod_RCA.pdf', 'dir': '_m0/13', 'linked': 2, 'len': 400000 },
    { 'url': 'http://www.aviadores.net/normativa/Orden_%2024_%20Abril_%201986_vueloULM.pdf', 'dir': '_m0/14', 'linked': 2, 'len': 130063 },
    { 'url': 'http://www.aviadores.net/normativa/orden_31_mayo_1982.pdf', 'dir': '_m0/15', 'linked': 2, 'len': 101203 },
    { 'url': 'http://www.aviadores.net/normativa/PROYECTO_ORDEN_ULTRALlGERO.pdf', 'dir': '_m0/16', 'linked': 2, 'len': 154233 },
    { 'url': 'http://www.aviadores.net/normativa/REAL_DECRETO_1591_ULM.pdf', 'dir': '_m0/17', 'linked': 2, 'len': 69252 },
    { 'url': 'http://www.aviadores.net/normativa/Real_Decreto_2876_ULM.pdf', 'dir': '_m0/18', 'linked': 2, 'len': 85325 },
    { 'url': 'http://www.aviadores.net/normativa/REGLAMENTO(CE)216-2009.pdf', 'dir': '_m0/19', 'linked': 2, 'len': 292354 },
    { 'url': 'http://www.aviadores.net/normativa/reglamento_circulacion.pdf', 'dir': '_m0/20', 'linked': 2, 'len': 400000 },
    { 'url': 'http://www.aviadores.net/normativa/resolucion_15_%20junio_1994.pdf', 'dir': '_m0/21', 'linked': 2, 'len': 59965 } ]
  },
  { 'mime': 'application/xhtml+xml', 'samples': [
    { 'url': 'http://www.aviadores.net/', 'dir': '_m1/0', 'linked': 2, 'len': 8319 },
    { 'url': 'http://www.aviadores.net/clippers_panam.html', 'dir': '_m1/1', 'linked': 2, 'len': 39678 },
    { 'url': 'http://www.aviadores.net/dornierdox.html', 'dir': '_m1/2', 'linked': 2, 'len': 26744 },
    { 'url': 'http://www.aviadores.net/enlaces.html', 'dir': '_m1/3', 'linked': 2, 'len': 972 },
    { 'url': 'http://www.aviadores.net/enlaces_asociaciones.html', 'dir': '_m1/4', 'linked': 2, 'len': 8650 },
    { 'url': 'http://www.aviadores.net/enlaces_fabricantes.html', 'dir': '_m1/5', 'linked': 2, 'len': 6733 },
    { 'url': 'http://www.aviadores.net/enlaces_fotografias.html', 'dir': '_m1/6', 'linked': 2, 'len': 4945 },
    { 'url': 'http://www.aviadores.net/enlaces_frame_cabecera.html', 'dir': '_m1/7', 'linked': 2, 'len': 1168 },
    { 'url': 'http://www.aviadores.net/enlaces_frame_contenido.html', 'dir': '_m1/8', 'linked': 2, 'len': 3453 },
    { 'url': 'http://www.aviadores.net/enlaces_frame_menu.html', 'dir': '_m1/9', 'linked': 2, 'len': 1624 },
    { 'url': 'http://www.aviadores.net/enlaces_paginastematicas.html', 'dir': '_m1/10', 'linked': 2, 'len': 6360 },
    { 'url': 'http://www.aviadores.net/enlaces_revistas.html', 'dir': '_m1/11', 'linked': 2, 'len': 9347 },
    { 'url': 'http://www.aviadores.net/enlaces_tiendas.html', 'dir': '_m1/12', 'linked': 2, 'len': 3511 },
    { 'url': 'http://www.aviadores.net/fairchild24.html', 'dir': '_m1/13', 'linked': 2, 'len': 11298 },
    { 'url': 'http://www.aviadores.net/fisherxp75.html', 'dir': '_m1/14', 'linked': 2, 'len': 12598 },
    { 'url': 'http://www.aviadores.net/galeria.html', 'dir': '_m1/15', 'linked': 2, 'len': 7512 },
    { 'url': 'http://www.aviadores.net/galeria_bilbao.html', 'dir': '_m1/16', 'linked': 2, 'len': 10512 },
    { 'url': 'http://www.aviadores.net/galeria_breitling.html', 'dir': '_m1/17', 'linked': 2, 'len': 12367 },
    { 'url': 'http://www.aviadores.net/galeria_dornier.html', 'dir': '_m1/18', 'linked': 2, 'len': 10670 },
    { 'url': 'http://www.aviadores.net/galeria_F24W.html', 'dir': '_m1/19', 'linked': 2, 'len': 6401 },
    { 'url': 'http://www.aviadores.net/galeria_menorca.html', 'dir': '_m1/20', 'linked': 2, 'len': 5178 },
    { 'url': 'http://www.aviadores.net/galeria_nieve.html', 'dir': '_m1/21', 'linked': 2, 'len': 16152 },
    { 'url': 'http://www.aviadores.net/galeria_RAF.html', 'dir': '_m1/22', 'linked': 2, 'len': 29382 },
    { 'url': 'http://www.aviadores.net/galeria_redbull.html', 'dir': '_m1/23', 'linked': 2, 'len': 8537 },
    { 'url': 'http://www.aviadores.net/ICAO-E.htm', 'dir': '_m1/24', 'linked': 2, 'len': 400000 },
    { 'url': 'http://www.aviadores.net/ICAO-GH.htm', 'dir': '_m1/25', 'linked': 2, 'len': 400000 },
    { 'url': 'http://www.aviadores.net/ICAO-K1.htm', 'dir': '_m1/26', 'linked': 2, 'len': 400000 },
    { 'url': 'http://www.aviadores.net/icao.htm', 'dir': '_m1/27', 'linked': 2, 'len': 22936 },
    { 'url': 'http://www.aviadores.net/informe.html', 'dir': '_m1/28', 'linked': 2, 'len': 7272 },
    { 'url': 'http://www.aviadores.net/informe_avionetas.html', 'dir': '_m1/29', 'linked': 2, 'len': 12311 },
    { 'url': 'http://www.aviadores.net/informe_elestudio.html', 'dir': '_m1/30', 'linked': 2, 'len': 6132 },
    { 'url': 'http://www.aviadores.net/informe_motores.html', 'dir': '_m1/31', 'linked': 2, 'len': 6427 },
    { 'url': 'http://www.aviadores.net/informe_ultraligeros.html', 'dir': '_m1/32', 'linked': 2, 'len': 15204 },
    { 'url': 'http://www.aviadores.net/maquinas.html', 'dir': '_m1/33', 'linked': 2, 'len': 7837 },
    { 'url': 'http://www.aviadores.net/meteo_frame_contenido.html', 'dir': '_m1/34', 'linked': 2, 'len': 3075 },
    { 'url': 'http://www.aviadores.net/meteo_frame_menu.html', 'dir': '_m1/35', 'linked': 2, 'len': 4592 },
    { 'url': 'http://www.aviadores.net/meteo_frame_menuhist.html', 'dir': '_m1/36', 'linked': 2, 'len': 2558 },
    { 'url': 'http://www.aviadores.net/normativa_frame_amateur.html', 'dir': '_m1/37', 'linked': 2, 'len': 3887 },
    { 'url': 'http://www.aviadores.net/normativa_frame_cabecera.html', 'dir': '_m1/38', 'linked': 2, 'len': 1364 },
    { 'url': 'http://www.aviadores.net/normativa_frame_contenido.html', 'dir': '_m1/39', 'linked': 2, 'len': 2961 },
    { 'url': 'http://www.aviadores.net/normativa_frame_jarfcl.html', 'dir': '_m1/40', 'linked': 2, 'len': 6056 },
    { 'url': 'http://www.aviadores.net/normativa_frame_rca.html', 'dir': '_m1/41', 'linked': 2, 'len': 3100 },
    { 'url': 'http://www.aviadores.net/normativa_frame_ulm.html', 'dir': '_m1/42', 'linked': 2, 'len': 4648 },
    { 'url': 'http://www.aviadores.net/rozas.html', 'dir': '_m1/43', 'linked': 2, 'len': 12925 },
    { 'url': 'http://www.aviadores.net/wright.html', 'dir': '_m1/44', 'linked': 2, 'len': 9202 },
    { 'url': 'http://www.aviadores.net/wright_audaciaycalculo.html', 'dir': '_m1/45', 'linked': 2, 'len': 5676 },
    { 'url': 'http://www.aviadores.net/wright_chanute.html', 'dir': '_m1/46', 'linked': 2, 'len': 8310 },
    { 'url': 'http://www.aviadores.net/wright_ejes.html', 'dir': '_m1/47', 'linked': 2, 'len': 6187 },
    { 'url': 'http://www.aviadores.net/wright_elvuelo.html', 'dir': '_m1/48', 'linked': 2, 'len': 5915 },
    { 'url': 'http://www.aviadores.net/wright_motor.html', 'dir': '_m1/49', 'linked': 2, 'len': 4758 },
    { 'url': 'http://www.aviadores.net/wright_pesoyempuje.html', 'dir': '_m1/50', 'linked': 2, 'len': 9740 },
    { 'url': 'http://www.aviadores.net/wright_preparativos.html', 'dir': '_m1/51', 'linked': 2, 'len': 7027 },
    { 'url': 'http://www.aviadores.net/wright_primerintento.html', 'dir': '_m1/52', 'linked': 2, 'len': 7063 },
    { 'url': 'http://www.aviadores.net/wright_vueloprueba.html', 'dir': '_m1/53', 'linked': 2, 'len': 5617 },
    { 'url': 'http://www.aviadores.net/wright_vuelossiguientes.html', 'dir': '_m1/54', 'linked': 2, 'len': 7084 },
    { 'url': 'http://www.aviadores.net/zero.html', 'dir': '_m1/55', 'linked': 2, 'len': 6303 },
    { 'url': 'http://www.aviadores.net/Zero_comparativas.html', 'dir': '_m1/56', 'linked': 2, 'len': 14972 },
    { 'url': 'http://www.aviadores.net/zero_descripcion.html', 'dir': '_m1/57', 'linked': 2, 'len': 12141 } ]
  },
  { 'mime': 'image/gif', 'samples': [
    { 'url': 'http://www.aviadores.net/images/logos_cabeceras/101airborne.gif', 'dir': '_m2/0', 'linked': 2, 'len': 1588 },
    { 'url': 'http://www.aviadores.net/images/logos_cabeceras/cabecera_enlaces.gif', 'dir': '_m2/1', 'linked': 2, 'len': 22344 },
    { 'url': 'http://www.aviadores.net/images/logos_cabeceras/cabecera_maquinas.gif', 'dir': '_m2/2', 'linked': 2, 'len': 32331 },
    { 'url': 'http://www.aviadores.net/images/logos_cabeceras/cabecera_normativa.gif', 'dir': '_m2/3', 'linked': 2, 'len': 7510 },
    { 'url': 'http://www.aviadores.net/images/logos_cabeceras/pie_relato.gif', 'dir': '_m2/4', 'linked': 2, 'len': 2682 },
    { 'url': 'http://www.aviadores.net/images/logos_cabeceras/tit_aviadores.gif', 'dir': '_m2/5', 'linked': 2, 'len': 576 },
    { 'url': 'http://www.aviadores.net/images/logos_cabeceras/tit_enlaces.gif', 'dir': '_m2/6', 'linked': 2, 'len': 501 },
    { 'url': 'http://www.aviadores.net/images/logos_cabeceras/tit_informe.gif', 'dir': '_m2/7', 'linked': 2, 'len': 681 },
    { 'url': 'http://www.aviadores.net/images/logos_cabeceras/tit_pilotaje.gif', 'dir': '_m2/8', 'linked': 2, 'len': 524 },
    { 'url': 'http://www.aviadores.net/images/logos_cabeceras/tit_wright.gif', 'dir': '_m2/9', 'linked': 2, 'len': 628 },
    { 'url': 'http://www.aviadores.net/images/logos_cabeceras/tit_zero.gif', 'dir': '_m2/10', 'linked': 2, 'len': 753 },
    { 'url': 'http://www.aviadores.net/images/piezas/atras2.gif', 'dir': '_m2/11', 'linked': 2, 'len': 1409 },
    { 'url': 'http://www.aviadores.net/images/piezas/bordegris_largoframe.gif', 'dir': '_m2/12', 'linked': 2, 'len': 2397 },
    { 'url': 'http://www.aviadores.net/images/piezas/bordemorado.gif', 'dir': '_m2/13', 'linked': 2, 'len': 502 },
    { 'url': 'http://www.aviadores.net/images/piezas/bordemorado_largo.gif', 'dir': '_m2/14', 'linked': 2, 'len': 531 },
    { 'url': 'http://www.aviadores.net/images/piezas/bordemorado_largoframe.gif', 'dir': '_m2/15', 'linked': 2, 'len': 619 },
    { 'url': 'http://www.aviadores.net/images/piezas/separador.gif', 'dir': '_m2/16', 'linked': 2, 'len': 127 },
    { 'url': 'http://www.aviadores.net/images/piezas/separador_fino.gif', 'dir': '_m2/17', 'linked': 2, 'len': 113 } ]
  },
  { 'mime': 'image/jpeg', 'samples': [
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_dornier1.jpg', 'dir': '_m3/0', 'linked': 2, 'len': 138000 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_dornier10.jpg', 'dir': '_m3/1', 'linked': 2, 'len': 162583 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_dornier14.jpg', 'dir': '_m3/2', 'linked': 2, 'len': 119202 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_dornier15.jpg', 'dir': '_m3/3', 'linked': 2, 'len': 113712 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_dornier2.jpg', 'dir': '_m3/4', 'linked': 2, 'len': 93055 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_dornier22.jpg', 'dir': '_m3/5', 'linked': 2, 'len': 44818 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_dornier1.jpg', 'dir': '_m3/6', 'linked': 2, 'len': 5435 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_dornier10.jpg', 'dir': '_m3/7', 'linked': 2, 'len': 7452 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_dornier11.jpg', 'dir': '_m3/8', 'linked': 2, 'len': 6603 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_dornier12.jpg', 'dir': '_m3/9', 'linked': 2, 'len': 6431 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_dornier13.jpg', 'dir': '_m3/10', 'linked': 2, 'len': 5894 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_dornier14.jpg', 'dir': '_m3/11', 'linked': 2, 'len': 5980 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_dornier15.jpg', 'dir': '_m3/12', 'linked': 2, 'len': 5901 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_dornier16.jpg', 'dir': '_m3/13', 'linked': 2, 'len': 5054 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_dornier17.jpg', 'dir': '_m3/14', 'linked': 2, 'len': 5703 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_dornier19.jpg', 'dir': '_m3/15', 'linked': 2, 'len': 6300 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_dornier2.jpg', 'dir': '_m3/16', 'linked': 2, 'len': 5341 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_dornier20.jpg', 'dir': '_m3/17', 'linked': 2, 'len': 5921 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_dornier21.jpg', 'dir': '_m3/18', 'linked': 2, 'len': 4392 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_dornier22.jpg', 'dir': '_m3/19', 'linked': 2, 'len': 2056 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_dornier3.jpg', 'dir': '_m3/20', 'linked': 2, 'len': 5109 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_dornier4.jpg', 'dir': '_m3/21', 'linked': 2, 'len': 4818 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_dornier6.jpg', 'dir': '_m3/22', 'linked': 2, 'len': 5968 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_dornier7.jpg', 'dir': '_m3/23', 'linked': 2, 'len': 6752 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_dornier8.jpg', 'dir': '_m3/24', 'linked': 2, 'len': 6935 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_RAF11.jpg', 'dir': '_m3/25', 'linked': 2, 'len': 5619 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_RAF12.jpg', 'dir': '_m3/26', 'linked': 2, 'len': 5904 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_RAF16.jpg', 'dir': '_m3/27', 'linked': 2, 'len': 6322 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_RAF19.jpg', 'dir': '_m3/28', 'linked': 2, 'len': 5781 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_RAF2.jpg', 'dir': '_m3/29', 'linked': 2, 'len': 7337 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_RAF20.jpg', 'dir': '_m3/30', 'linked': 2, 'len': 5803 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_RAF21.jpg', 'dir': '_m3/31', 'linked': 2, 'len': 6326 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_RAF24.jpg', 'dir': '_m3/32', 'linked': 2, 'len': 5171 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_RAF26.jpg', 'dir': '_m3/33', 'linked': 2, 'len': 6894 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_RAF27.jpg', 'dir': '_m3/34', 'linked': 2, 'len': 7306 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_RAF29.jpg', 'dir': '_m3/35', 'linked': 2, 'len': 7588 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_RAF32.jpg', 'dir': '_m3/36', 'linked': 2, 'len': 6455 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_RAF38.jpg', 'dir': '_m3/37', 'linked': 2, 'len': 6677 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_RAF41.jpg', 'dir': '_m3/38', 'linked': 2, 'len': 6702 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_RAF43.jpg', 'dir': '_m3/39', 'linked': 2, 'len': 7665 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_RAF46.jpg', 'dir': '_m3/40', 'linked': 2, 'len': 5712 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_RAF48.jpg', 'dir': '_m3/41', 'linked': 2, 'len': 6529 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_RAF6.jpg', 'dir': '_m3/42', 'linked': 2, 'len': 8008 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_RAF8.jpg', 'dir': '_m3/43', 'linked': 2, 'len': 5659 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_zeppelin11.jpg', 'dir': '_m3/44', 'linked': 2, 'len': 3999 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_zeppelin14.jpg', 'dir': '_m3/45', 'linked': 2, 'len': 4897 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_zeppelin15.jpg', 'dir': '_m3/46', 'linked': 2, 'len': 5200 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_zeppelin2.jpg', 'dir': '_m3/47', 'linked': 2, 'len': 3870 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_zeppelin3.jpg', 'dir': '_m3/48', 'linked': 2, 'len': 5043 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_zeppelin5.jpg', 'dir': '_m3/49', 'linked': 2, 'len': 4513 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_zeppelin7.jpg', 'dir': '_m3/50', 'linked': 2, 'len': 7311 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_min_zeppelin8.jpg', 'dir': '_m3/51', 'linked': 2, 'len': 7728 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_RAF24.jpg', 'dir': '_m3/52', 'linked': 2, 'len': 77610 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_RAF29.jpg', 'dir': '_m3/53', 'linked': 2, 'len': 177303 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_RAF43.jpg', 'dir': '_m3/54', 'linked': 2, 'len': 150604 },
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_zeppelin11.jpg', 'dir': '_m3/55', 'linked': 2, 'len': 102750 },
    { 'url': 'http://www.aviadores.net/images/logos_cabeceras/cabecera_amateur.jpg', 'dir': '_m3/56', 'linked': 2, 'len': 12658 },
    { 'url': 'http://www.aviadores.net/images/logos_cabeceras/cabecera_aviadores.jpg', 'dir': '_m3/57', 'linked': 2, 'len': 12671 },
    { 'url': 'http://www.aviadores.net/images/logos_cabeceras/cabecera_bilbao.jpg', 'dir': '_m3/58', 'linked': 2, 'len': 11536 },
    { 'url': 'http://www.aviadores.net/images/logos_cabeceras/cabecera_breitling.jpg', 'dir': '_m3/59', 'linked': 2, 'len': 9995 },
    { 'url': 'http://www.aviadores.net/images/logos_cabeceras/cabecera_dox.jpg', 'dir': '_m3/60', 'linked': 2, 'len': 7923 },
    { 'url': 'http://www.aviadores.net/images/logos_cabeceras/cabecera_galeria.jpg', 'dir': '_m3/61', 'linked': 2, 'len': 8709 },
    { 'url': 'http://www.aviadores.net/images/logos_cabeceras/cabecera_galeria_IWM.jpg', 'dir': '_m3/62', 'linked': 2, 'len': 11512 },
    { 'url': 'http://www.aviadores.net/images/logos_cabeceras/cabecera_informe.jpg', 'dir': '_m3/63', 'linked': 2, 'len': 10944 },
    { 'url': 'http://www.aviadores.net/images/logos_cabeceras/cabecera_meteo.jpg', 'dir': '_m3/64', 'linked': 2, 'len': 10150 },
    { 'url': 'http://www.aviadores.net/images/logos_cabeceras/cabecera_nieve.jpg', 'dir': '_m3/65', 'linked': 2, 'len': 6697 },
    { 'url': 'http://www.aviadores.net/images/logos_cabeceras/cabecera_pilotaje.jpg', 'dir': '_m3/66', 'linked': 2, 'len': 6384 },
    { 'url': 'http://www.aviadores.net/images/logos_cabeceras/cabecera_redbull.jpg', 'dir': '_m3/67', 'linked': 2, 'len': 7941 },
    { 'url': 'http://www.aviadores.net/images/logos_cabeceras/cabecera_ultraligeros.jpg', 'dir': '_m3/68', 'linked': 2, 'len': 7816 },
    { 'url': 'http://www.aviadores.net/images/logos_cabeceras/cabecera_xp75.jpg', 'dir': '_m3/69', 'linked': 2, 'len': 9769 } ]
  },
  { 'mime': 'image/png', 'samples': [
    { 'url': 'http://www.aviadores.net/images/logos_cabeceras/tit_meteo.png', 'dir': '_m4/0', 'linked': 2, 'len': 23683 } ]
  },
  { 'mime': 'text/css', 'samples': [
    { 'url': 'http://www.aviadores.net/estilo_aviadores.css', 'dir': '_m5/0', 'linked': 2, 'len': 2578 } ]
  },
  { 'mime': 'text/html', 'samples': [
    { 'url': 'http://www.aviadores.net/ICAO-AD.htm', 'dir': '_m6/0', 'linked': 2, 'len': 400000 } ]
  },
  { 'mime': 'text/plain', 'samples': [
    { 'url': 'http://www.aviadores.net/images/logos_cabeceras/cabecera_estudio.gif', 'dir': '_m7/0', 'linked': 2, 'len': 5926 } ]
  }
];

var issue_samples = [
  { 'severity': 3, 'type': 40201, 'samples': [
    { 'url': 'http://www.aviadores.net/meteo_frame_menu.html', 'extra': 'http://www.aviadores.eu/meteo.php', 'sid': '0', 'dir': '_i0/0' },
    { 'url': 'http://www.aviadores.net/meteo_frame_menu.html', 'extra': 'http://www.aviadores.eu/fotos.php', 'sid': '0', 'dir': '_i0/1' },
    { 'url': 'http://www.aviadores.net/meteo_frame_menuhist.html', 'extra': 'http://meteocentre.com/cgi-bin/get_sao_stn', 'sid': '0', 'dir': '_i0/2' } ]
  },
  { 'severity': 1, 'type': 20102, 'samples': [
    { 'url': 'http://www.aviadores.net/images/ilustraciones/galeria_RAF51.jpg', 'extra': 'Child node limit exceeded', 'sid': '0', 'dir': '_i1/0' } ]
  },
  { 'severity': 0, 'type': 10901, 'samples': [
    { 'url': 'http://www.aviadores.net/normativa/CS-23.pdf', 'extra': '', 'sid': '0', 'dir': '_i2/0' },
    { 'url': 'http://www.aviadores.net/normativa/JARFCL1Indice1.pdf', 'extra': '', 'sid': '0', 'dir': '_i2/1' },
    { 'url': 'http://www.aviadores.net/normativa/JARFCL1SUBB.pdf', 'extra': '', 'sid': '0', 'dir': '_i2/2' },
    { 'url': 'http://www.aviadores.net/normativa/JARFCL1SUBC.pdf', 'extra': '', 'sid': '0', 'dir': '_i2/3' },
    { 'url': 'http://www.aviadores.net/normativa/JARFCL1SUBE.pdf', 'extra': '', 'sid': '0', 'dir': '_i2/4' },
    { 'url': 'http://www.aviadores.net/normativa/JARFCL1SUBF.pdf', 'extra': '', 'sid': '0', 'dir': '_i2/5' },
    { 'url': 'http://www.aviadores.net/normativa/JARFCL3SUBA.pdf', 'extra': '', 'sid': '0', 'dir': '_i2/6' },
    { 'url': 'http://www.aviadores.net/normativa/JARFCL3SUBC.pdf', 'extra': '', 'sid': '0', 'dir': '_i2/7' },
    { 'url': 'http://www.aviadores.net/normativa/mantenimiento_aeronaves2.pdf', 'extra': '', 'sid': '0', 'dir': '_i2/8' },
    { 'url': 'http://www.aviadores.net/normativa/ord_pre_2733_06_mod_RCA.pdf', 'extra': '', 'sid': '0', 'dir': '_i2/9' },
    { 'url': 'http://www.aviadores.net/normativa/ord_pre_2912_05_mod_RCA.pdf', 'extra': '', 'sid': '0', 'dir': '_i2/10' },
    { 'url': 'http://www.aviadores.net/normativa/ord_pre_4063_06_mod_RCA.pdf', 'extra': '', 'sid': '0', 'dir': '_i2/11' },
    { 'url': 'http://www.aviadores.net/normativa/Orden_%2024_%20Abril_%201986_vueloULM.pdf', 'extra': '', 'sid': '0', 'dir': '_i2/12' },
    { 'url': 'http://www.aviadores.net/normativa/orden_31_mayo_1982.pdf', 'extra': '', 'sid': '0', 'dir': '_i2/13' },
    { 'url': 'http://www.aviadores.net/normativa/REAL_DECRETO_1591_ULM.pdf', 'extra': '', 'sid': '0', 'dir': '_i2/14' },
    { 'url': 'http://www.aviadores.net/normativa/Real_Decreto_2876_ULM.pdf', 'extra': '', 'sid': '0', 'dir': '_i2/15' },
    { 'url': 'http://www.aviadores.net/normativa/REGLAMENTO(CE)216-2009.pdf', 'extra': '', 'sid': '0', 'dir': '_i2/16' },
    { 'url': 'http://www.aviadores.net/normativa/resolucion_15_%20junio_1994.pdf', 'extra': '', 'sid': '0', 'dir': '_i2/17' },
    { 'url': 'http://www.aviadores.net/fairchild24.html', 'extra': '', 'sid': '0', 'dir': '_i2/18' },
    { 'url': 'http://www.aviadores.net/fisherxp75.html', 'extra': '', 'sid': '0', 'dir': '_i2/19' },
    { 'url': 'http://www.aviadores.net/fw190.html', 'extra': '', 'sid': '0', 'dir': '_i2/20' },
    { 'url': 'http://www.aviadores.net/galeria_F24W.html', 'extra': '', 'sid': '0', 'dir': '_i2/21' },
    { 'url': 'http://www.aviadores.net/galeria_garray08.html', 'extra': '', 'sid': '0', 'dir': '_i2/22' },
    { 'url': 'http://www.aviadores.net/galeria_I153.html', 'extra': '', 'sid': '0', 'dir': '_i2/23' },
    { 'url': 'http://www.aviadores.net/ICAO-K1.htm', 'extra': '', 'sid': '0', 'dir': '_i2/24' },
    { 'url': 'http://www.aviadores.net/ICAO-S2.htm', 'extra': '', 'sid': '0', 'dir': '_i2/25' } ]
  },
  { 'severity': 0, 'type': 10803, 'samples': [
    { 'url': 'http://www.aviadores.net/images/logos_cabeceras/cabecera_estudio.gif', 'extra': '', 'sid': '0', 'dir': '_i3/0' },
    { 'url': 'http://www.aviadores.net/normativa/convenio_chicago.pdf', 'extra': '', 'sid': '0', 'dir': '_i3/1' },
    { 'url': 'http://www.aviadores.net/normativa/CS-23.pdf', 'extra': '', 'sid': '0', 'dir': '_i3/2' },
    { 'url': 'http://www.aviadores.net/normativa/entidades_colaboradoras.pdf', 'extra': '', 'sid': '0', 'dir': '_i3/3' },
    { 'url': 'http://www.aviadores.net/normativa/EscritoParteMNTAC.pdf', 'extra': '', 'sid': '0', 'dir': '_i3/4' },
    { 'url': 'http://www.aviadores.net/normativa/JARFCL1Indice1.pdf', 'extra': '', 'sid': '0', 'dir': '_i3/5' },
    { 'url': 'http://www.aviadores.net/normativa/JARFCL1SUBB.pdf', 'extra': '', 'sid': '0', 'dir': '_i3/6' },
    { 'url': 'http://www.aviadores.net/normativa/JARFCL1SUBC.pdf', 'extra': '', 'sid': '0', 'dir': '_i3/7' },
    { 'url': 'http://www.aviadores.net/normativa/JARFCL1SUBE.pdf', 'extra': '', 'sid': '0', 'dir': '_i3/8' },
    { 'url': 'http://www.aviadores.net/normativa/JARFCL1SUBF.pdf', 'extra': '', 'sid': '0', 'dir': '_i3/9' },
    { 'url': 'http://www.aviadores.net/normativa/JARFCL3SUBA.pdf', 'extra': '', 'sid': '0', 'dir': '_i3/10' },
    { 'url': 'http://www.aviadores.net/normativa/JARFCL3SUBC.pdf', 'extra': '', 'sid': '0', 'dir': '_i3/11' },
    { 'url': 'http://www.aviadores.net/normativa/mantenimiento_aeronaves2.pdf', 'extra': '', 'sid': '0', 'dir': '_i3/12' },
    { 'url': 'http://www.aviadores.net/normativa/ord_pre_2733_06_mod_RCA.pdf', 'extra': '', 'sid': '0', 'dir': '_i3/13' },
    { 'url': 'http://www.aviadores.net/normativa/ord_pre_2912_05_mod_RCA.pdf', 'extra': '', 'sid': '0', 'dir': '_i3/14' },
    { 'url': 'http://www.aviadores.net/normativa/ord_pre_4063_06_mod_RCA.pdf', 'extra': '', 'sid': '0', 'dir': '_i3/15' },
    { 'url': 'http://www.aviadores.net/normativa/Orden_%2024_%20Abril_%201986_vueloULM.pdf', 'extra': '', 'sid': '0', 'dir': '_i3/16' },
    { 'url': 'http://www.aviadores.net/normativa/orden_31_mayo_1982.pdf', 'extra': '', 'sid': '0', 'dir': '_i3/17' },
    { 'url': 'http://www.aviadores.net/normativa/PROYECTO_ORDEN_ULTRALlGERO.pdf', 'extra': '', 'sid': '0', 'dir': '_i3/18' },
    { 'url': 'http://www.aviadores.net/normativa/REAL_DECRETO_1591_ULM.pdf', 'extra': '', 'sid': '0', 'dir': '_i3/19' },
    { 'url': 'http://www.aviadores.net/normativa/Real_Decreto_2876_ULM.pdf', 'extra': '', 'sid': '0', 'dir': '_i3/20' },
    { 'url': 'http://www.aviadores.net/normativa/REGLAMENTO(CE)216-2009.pdf', 'extra': '', 'sid': '0', 'dir': '_i3/21' },
    { 'url': 'http://www.aviadores.net/normativa/reglamento_circulacion.pdf', 'extra': '', 'sid': '0', 'dir': '_i3/22' },
    { 'url': 'http://www.aviadores.net/normativa/resolucion_15_%20junio_1994.pdf', 'extra': '', 'sid': '0', 'dir': '_i3/23' },
    { 'url': 'http://www.aviadores.net/estilo_aviadores.css', 'extra': '', 'sid': '0', 'dir': '_i3/24' } ]
  },
  { 'severity': 0, 'type': 10801, 'samples': [
    { 'url': 'http://www.aviadores.net/images/logos_cabeceras/cabecera_estudio.gif', 'extra': 'text/plain', 'sid': '0', 'dir': '_i4/0' } ]
  },
  { 'severity': 0, 'type': 10205, 'samples': [
    { 'url': 'http://www.aviadores.net/sfi9876', 'extra': '', 'sid': '0', 'dir': '_i5/0' } ]
  },
  { 'severity': 0, 'type': 10202, 'samples': [
    { 'url': 'http://www.aviadores.net/', 'extra': 'Apache/2.4.41 (Unix)', 'sid': '0', 'dir': '_i6/0' } ]
  }
];

